# ベースとなるDockerイメージ指定
FROM golang:latest
# コンテナ内に作業ディレクトリを作成
RUN mkdir /go/src/work
# PostgreSQLのドライバ入手
RUN go get github.com/lib/pq
# コンテナログイン時のディレクトリ指定
WORKDIR /go/src/work
# ホストのファイルをコンテナの作業ディレクトリに移行
ADD . /go/src/work
# 他のコンテナに対して8080番ポートを開く
EXPOSE 8080
